on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    branches:
      - main

name: Build

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cprecioso/action-prepare-node@v1

      - run: yarn run pack
      - uses: actions/upload-artifact@v4
        with:
          name: packages
          path: out/*
          if-no-files-found: error

      - run: yarn run build:docs
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs/
